"""add worker lease and retry fields

Revision ID: 05645529560d
Revises: 48aa85e92785
Create Date: 2026-09-05 22:15:07.038181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05645529560d'
down_revision: Union[str, Sequence[str], None] = '48aa85e92785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_jobs', sa.Column('worker_id', sa.String(length=64), nullable=True))
    op.add_column('review_jobs', sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('review_jobs', sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_review_jobs_lease_expires_at'), 'review_jobs', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_review_jobs_next_retry_at'), 'review_jobs', ['next_retry_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_jobs_next_retry_at'), table_name='review_jobs')
    op.drop_index(op.f('ix_review_jobs_lease_expires_at'), table_name='review_jobs')
    op.drop_column('review_jobs', 'next_retry_at')
    op.drop_column('review_jobs', 'lease_expires_at')
    op.drop_column('review_jobs', 'worker_id')
    # ### end Alembic commands ###
