"""create review_jobs table

Revision ID: 48aa85e92785
Revises: 
Create Date: 2026-09-05 21:51:05.667589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48aa85e92785'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('delivery_id', sa.String(length=128), nullable=True),
    sa.Column('repo_full_name', sa.String(length=255), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('head_sha', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_jobs_delivery_id'), 'review_jobs', ['delivery_id'], unique=True)
    op.create_index(op.f('ix_review_jobs_head_sha'), 'review_jobs', ['head_sha'], unique=False)
    op.create_index(op.f('ix_review_jobs_pr_number'), 'review_jobs', ['pr_number'], unique=False)
    op.create_index(op.f('ix_review_jobs_repo_full_name'), 'review_jobs', ['repo_full_name'], unique=False)
    op.create_index(op.f('ix_review_jobs_status'), 'review_jobs', ['status'], unique=False)
    op.create_index('uq_active_or_completed_review', 'review_jobs', ['repo_full_name', 'pr_number', 'head_sha'], unique=True, postgresql_where=sa.text("status IN ('queued', 'in_progress', 'completed')"), sqlite_where=sa.text("status IN ('queued', 'in_progress', 'completed')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_or_completed_review', table_name='review_jobs', postgresql_where=sa.text("status IN ('queued', 'in_progress', 'completed')"), sqlite_where=sa.text("status IN ('queued', 'in_progress', 'completed')"))
    op.drop_index(op.f('ix_review_jobs_status'), table_name='review_jobs')
    op.drop_index(op.f('ix_review_jobs_repo_full_name'), table_name='review_jobs')
    op.drop_index(op.f('ix_review_jobs_pr_number'), table_name='review_jobs')
    op.drop_index(op.f('ix_review_jobs_head_sha'), table_name='review_jobs')
    op.drop_index(op.f('ix_review_jobs_delivery_id'), table_name='review_jobs')
    op.drop_table('review_jobs')
    # ### end Alembic commands ###
