"""add_claim_lookup_index

Revision ID: fe5c1dc21897
Revises: 6dc3415dba2d
Create Date: 2026-09-06 13:30:16.551293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe5c1dc21897'
down_revision: Union[str, Sequence[str], None] = '6dc3415dba2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_review_jobs_claim_lookup', 'review_jobs', ['status', 'next_retry_at', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_review_jobs_claim_lookup', table_name='review_jobs')
    # ### end Alembic commands ###
